"""Reconciler loop — diff desired (YAML on disk) vs actual (sbx API).

Runs as an asyncio task in the daemon's event loop. Tick interval comes
from ``DaemonConfig.reconciler_interval_seconds`` (default 30s).

Per-tick algorithm:

  1. Walk ``~/.sopify/encm/rules/`` → load every YAML → ``NetworkRule``
  2. Compute SHA-256 of each file's contents (so we can skip unchanged
     files cheaply on the next tick)
  3. Fetch ``GET /policy/rules`` from sandboxd
  4. Diff against the saved ``.state/sync.yaml``:
     - New files / changed checksum → POST to sandboxd
     - Deleted files (file gone but state had handles) → DELETE from sandboxd
     - sbx rules with no matching ENCM file → record as drift
  5. Persist updated ``.state/sync.yaml`` atomically under ``filelock``

The loop never raises — exceptions are logged + recorded in
``last_error`` on the affected rule's sync state.
"""
from __future__ import annotations

import asyncio
import hashlib
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

import yaml
from filelock import FileLock

from . import paths
from .rule_writer import RuleFileWriter
from .sbx_backend import (
    ISandboxBackend,
    PolicyRuleApplied,
    PolicyRuleRequest,
)
from .schema import (
    DriftObservation,
    NetworkRule,
    RuleHandle,
    RuleSyncState,
    SyncState,
)

log = logging.getLogger(__name__)


def _checksum(path: Path) -> str:
    return "sha256:" + hashlib.sha256(path.read_bytes()).hexdigest()


def _load_sync_state() -> SyncState:
    sf = paths.sync_state_file()
    if not sf.exists():
        return SyncState()
    try:
        data = yaml.safe_load(sf.read_text(encoding="utf-8")) or {}
        return SyncState.model_validate(data)
    except Exception:
        log.exception("sync.yaml unreadable, starting from empty state")
        return SyncState()


def _save_sync_state(state: SyncState) -> None:
    sf = paths.sync_state_file()
    sf.parent.mkdir(parents=True, exist_ok=True)
    lock = FileLock(str(paths.sync_state_lock_file()), timeout=5)
    with lock:
        tmp = sf.with_suffix(sf.suffix + ".tmp")
        tmp.write_text(
            "# Auto-generated by sopify reconciler — do not edit by hand.\n"
            + yaml.safe_dump(state.model_dump(mode="json"), sort_keys=False),
            encoding="utf-8",
        )
        tmp.replace(sf)


def _rule_to_requests(rule: NetworkRule) -> list[PolicyRuleRequest]:
    """Fan one YAML rule out to one sandboxd request per pattern.

    sandboxd takes a list of `resources`, so we COULD collapse all
    patterns into one rule — but per-pattern handles make drift detection
    + per-pattern rate-limit (Week 4) much simpler. Trade tracking
    overhead for observability.
    """
    return [
        PolicyRuleRequest(
            name=f"{rule.metadata.name}--{_pattern_slug(pat)}",
            resource_type="network",
            decision=rule.spec.decision,
            resources=(pat,),
            scope=rule.metadata.scope,
            sandbox_id=rule.metadata.sandbox_id,
            labels={
                "encm/source": rule.metadata.name,
                "encm/created_by": rule.metadata.created_by,
                **(rule.metadata.labels or {}),
            },
        )
        for pat in rule.spec.patterns
    ]


def _pattern_slug(pat: str) -> str:
    """Filename-safe + sandboxd-name-safe variant of an arbitrary pattern."""
    import re
    return re.sub(r"[^a-z0-9-]+", "-", pat.lower()).strip("-")[:32] or "p"


# Known sbx baseline rules — emitted by sandboxd itself, never user-created.
# We don't try to manage these, and they don't count as drift.
#
# Add new entries here when sbx ships another built-in (the contract test
# suite will surface them by failing). Match by name AND a resources
# fingerprint so a coincidentally-named user rule doesn't get filtered.
_SBX_BASELINE = (
    ("default-allow-all", ("**",)),
)


def _is_sbx_baseline(rule) -> bool:  # type: ignore[no-untyped-def]
    """True if this rule is part of sbx's built-in baseline OR a kit-managed
    rule that ENCM shouldn't try to compete with.

    Categories filtered out of drift detection:

      1. ``default-allow-all`` (and any future `default-*`) — sbx's
         own catch-all.
      2. Kit-managed rules — sbx materialises every kit's
         ``allowedDomains`` block as a rule with **name** ``kit:<sandbox-id>``
         and a non-null ``sandbox_id`` (HTTP API also tags origin as
         ``"scoped"``, but the name+sandbox_id combo is the most stable
         discriminator — verified against sandboxd 0.29 on 2026-05-24).
    """
    # Known builtins
    for name, resources in _SBX_BASELINE:
        if rule.name == name and tuple(rule.resources) == resources:
            return True
    # Future builtins
    if rule.name.startswith("default-") and rule.origin in ("default", "system"):
        return True
    # Kit-managed: name prefix `kit:` is sbx's literal convention.
    if rule.name.startswith("kit:"):
        return True
    # Belt-and-braces: any sandbox-scoped rule with a populated sandbox_id
    # that ENCM didn't write (ENCM rules for sandboxes get unique slugs
    # in their name, not the bare sandbox id).
    if rule.sandbox_id and rule.origin in ("scoped", "sandbox", "kit"):
        return True
    if rule.origin.startswith("sandbox:"):  # CLI-style format, kept for resilience
        return True
    return False


class Reconciler:
    """One reconciler per daemon. Owns the sync state."""

    def __init__(self, backend: ISandboxBackend) -> None:
        self._backend = backend
        self._writer = RuleFileWriter()
        self._tick_now = asyncio.Event()
        self._stop = asyncio.Event()
        self._last_tick_at: Optional[datetime] = None
        self._last_error: Optional[str] = None

    @property
    def last_tick_at(self) -> Optional[datetime]:
        return self._last_tick_at

    @property
    def last_error(self) -> Optional[str]:
        return self._last_error

    def kick(self) -> None:
        """Force an immediate tick (used by ``POST /api/v1/reconcile``)."""
        self._tick_now.set()

    def stop(self) -> None:
        self._stop.set()
        self._tick_now.set()

    async def run_forever(self, interval_seconds: float) -> None:
        """Main loop. Catches every exception so the task never dies."""
        while not self._stop.is_set():
            try:
                await self.tick_once()
            except Exception as exc:  # noqa: BLE001 — defensive
                log.exception("reconciler tick failed")
                self._last_error = f"{type(exc).__name__}: {exc}"
            try:
                await asyncio.wait_for(self._tick_now.wait(), timeout=interval_seconds)
            except asyncio.TimeoutError:
                pass
            self._tick_now.clear()

    async def tick_once(self) -> SyncState:
        """One reconciliation pass. Returns the new sync state."""
        state = _load_sync_state()
        # Index existing state by source path for O(1) lookup
        old: dict[str, RuleSyncState] = {r.source_path: r for r in state.rules}

        # Walk the rules dir
        desired: list[tuple[Path, NetworkRule, str]] = []
        for path in sorted(paths.rules_dir().rglob("*.yaml")):
            try:
                rule = self._writer.read(path)
            except Exception as exc:  # noqa: BLE001
                log.warning("skipping malformed rule file %s: %s", path, exc)
                continue
            desired.append((path, rule, _checksum(path)))

        actual = await self._backend.list_rules()
        actual_by_name: dict[str, PolicyRuleApplied] = {r.name: r for r in actual}

        new_states: list[RuleSyncState] = []
        applied_handle_ids: set[str] = set()

        # Apply / refresh desired rules
        for path, rule, checksum in desired:
            rel = str(path.relative_to(paths.encm_root()))
            existing = old.get(rel)
            unchanged = existing is not None and existing.checksum == checksum
            if unchanged:
                # Verify handles still exist; if any are gone, fall through
                # to re-apply.
                missing = [
                    h for h in existing.sbx_handles
                    if h.sbx_rule_id not in {r.id for r in actual}
                ]
                if not missing:
                    new_states.append(existing)
                    applied_handle_ids.update(h.sbx_rule_id for h in existing.sbx_handles)
                    continue

            handles: list[RuleHandle] = []
            error: Optional[str] = None
            try:
                for req in _rule_to_requests(rule):
                    # Idempotent re-apply: if a handle with the same name
                    # exists, remove it first so sandboxd doesn't 409.
                    existing_hit = actual_by_name.get(req.name)
                    if existing_hit:
                        try:
                            await self._backend.remove_rule(existing_hit.id)
                        except Exception as exc:  # noqa: BLE001
                            log.warning("pre-replace remove failed for %s: %s", req.name, exc)
                    applied = await self._backend.apply_rule(req)
                    handles.append(RuleHandle(sbx_rule_id=applied.id, pattern=req.resources[0]))
                    applied_handle_ids.add(applied.id)
            except Exception as exc:  # noqa: BLE001
                log.exception("apply failed for %s", rel)
                error = f"{type(exc).__name__}: {exc}"

            new_states.append(RuleSyncState(
                source_path=rel,
                checksum=checksum,
                sbx_handles=handles,
                last_applied_at=datetime.now(timezone.utc),
                sync_state="applied" if not error else "error",
                last_error=error,
            ))

        # Remove rules that were deleted from disk since last tick
        desired_paths = {str(p.relative_to(paths.encm_root())) for p, _, _ in desired}
        for old_path, old_state in old.items():
            if old_path in desired_paths:
                continue
            for handle in old_state.sbx_handles:
                try:
                    await self._backend.remove_rule(handle.sbx_rule_id)
                except Exception as exc:  # noqa: BLE001
                    log.warning("remove failed for %s: %s", handle.sbx_rule_id, exc)

        # Drift: sbx-side rules that ENCM doesn't know about.
        #
        # Filter out sbx's built-in baseline rule. Real sandboxd (verified
        # 2026-05-24) tags it as ``origin=local`` not ``origin=default`` —
        # the OpenAPI mini-spec guessed wrong. Match by name + resource
        # pattern instead, which is stable across sbx versions.
        drift: list[DriftObservation] = []
        for rule in actual:
            if rule.id in applied_handle_ids:
                continue
            if _is_sbx_baseline(rule):
                continue
            drift.append(DriftObservation(
                sbx_rule_id=rule.id,
                detected_at=datetime.now(timezone.utc),
                reason=f"sbx rule {rule.name!r} not tracked by ENCM",
                resources=list(rule.resources),
                decision=rule.decision,  # type: ignore[arg-type]
            ))

        new_state = SyncState(
            rules=new_states,
            drift_observations=drift,
            last_reconcile_at=datetime.now(timezone.utc),
        )
        _save_sync_state(new_state)
        self._last_tick_at = datetime.now(timezone.utc)
        self._last_error = None
        return new_state
