#!/usr/bin/env bash
# sopify-encm container entrypoint.
#
# Boots mitmproxy with the HTTP/HTTPS addon listening on $ENCM_HTTP_PROXY_PORT.
# CA cert is expected at $ENCM_CA_DIR/ca.crt (generated by `sopify install`
# on the host and mounted in). Policy lives at $ENCM_POLICY_PATH and is
# hot-reloaded by the addon's PolicyStore.
#
# Logs go to stdout (audit log = separate JSONL files under $ENCM_AUDIT_DIR).

set -euo pipefail

# ── validate mounts ──────────────────────────────────────────────────
if [[ ! -f "$ENCM_CA_DIR/ca.crt" ]]; then
    echo "encm: missing CA cert at $ENCM_CA_DIR/ca.crt — run 'sopify install' on host first" >&2
    exit 64
fi
if [[ ! -f "$ENCM_CA_DIR/ca.key" ]]; then
    echo "encm: missing CA key at $ENCM_CA_DIR/ca.key" >&2
    exit 64
fi

# Validate the policy file. Host installer (sopify install) is responsible
# for migrating v1 → v2 BEFORE the container boots — the mount is read-only
# so writes from inside the container would fail (bind-mount inode trick
# also breaks atomic rename). Fail-fast here if the schema is wrong rather
# than silently running with no policy.
PYTHONPATH=/opt/encm \
    /opt/encm/.venv/bin/python -c "from sopify_encm.schema import load_policy; \
                                    p = load_policy('$ENCM_POLICY_PATH'); \
                                    print(f'encm: policy loaded ({len(p.rules)} rules)')"

# Pre-build mitmproxy's confdir from the mounted CA. mitmproxy expects the
# combined PEM (key + cert) in a single file named `mitmproxy-ca.pem`.
mkdir -p /home/encm/.mitmproxy
cp "$ENCM_CA_DIR/ca-bundle.pem" /home/encm/.mitmproxy/mitmproxy-ca.pem
chmod 600 /home/encm/.mitmproxy/mitmproxy-ca.pem
# mitmproxy also looks for ca cert + key as separate files
cp "$ENCM_CA_DIR/ca.crt" /home/encm/.mitmproxy/mitmproxy-ca-cert.pem
cp "$ENCM_CA_DIR/ca.key" /home/encm/.mitmproxy/mitmproxy-ca-cert.key

# Background: audit log retention rotator — runs every hour
(
    while true; do
        sleep 3600
        PYTHONPATH=/opt/encm /opt/encm/.venv/bin/python -c \
            "from sopify_encm.audit import purge_old_logs; \
             import os; \
             purge_old_logs(os.environ['ENCM_AUDIT_DIR'], \
                            int(os.environ.get('ENCM_RETENTION_DAYS','30')))"
    done
) &

# Foreground: mitmproxy
exec /opt/encm/.venv/bin/mitmdump \
    --listen-port "$ENCM_HTTP_PROXY_PORT" \
    --set confdir=/home/encm/.mitmproxy \
    --set block_global=false \
    --scripts /opt/encm/sopify_encm/proxy/http_proxy.py
